version: '3.8'

services:
  web:
    image: "kasramp/kindler:${IMAGE_TAG:-latest}"
    environment:
      REDIS_URL: ${REDIS_URL}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8181:8181"
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/healthz/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s

networks:
  shared-network:
    external: true